/**
 * Build Validation Tests for BlackRoad OS Docs
 *
 * Validates that the Docusaurus site configuration is sound:
 *  - docusaurus.config.ts exists and exports a valid config
 *  - sidebars.ts exports properly
 *  - All docs referenced by autogenerated sidebar have valid frontmatter
 *  - Required static assets exist
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');

describe('Docusaurus config', () => {
  const configPath = path.join(ROOT, 'docusaurus.config.ts');

  test('docusaurus.config.ts exists', () => {
    expect(fs.existsSync(configPath)).toBe(true);
  });

  test('docusaurus.config.ts is not empty', () => {
    const content = fs.readFileSync(configPath, 'utf-8');
    expect(content.length).toBeGreaterThan(100);
  });

  test('config exports a default object', () => {
    const content = fs.readFileSync(configPath, 'utf-8');
    expect(content).toMatch(/export default/);
  });

  test('config contains required fields', () => {
    const content = fs.readFileSync(configPath, 'utf-8');
    expect(content).toMatch(/title:/);
    expect(content).toMatch(/url:/);
    expect(content).toMatch(/baseUrl:/);
  });
});

describe('Sidebars', () => {
  const sidebarsPath = path.join(ROOT, 'sidebars.ts');

  test('sidebars.ts exists', () => {
    expect(fs.existsSync(sidebarsPath)).toBe(true);
  });

  test('sidebars.ts exports default', () => {
    const content = fs.readFileSync(sidebarsPath, 'utf-8');
    expect(content).toMatch(/export default/);
  });

  test('sidebars.ts imports SidebarsConfig type', () => {
    const content = fs.readFileSync(sidebarsPath, 'utf-8');
    expect(content).toMatch(/SidebarsConfig/);
  });
});

describe('Docs directory', () => {
  const docsDir = path.join(ROOT, 'docs');

  test('docs/ directory exists', () => {
    expect(fs.existsSync(docsDir)).toBe(true);
    expect(fs.statSync(docsDir).isDirectory()).toBe(true);
  });

  test('docs/ contains at least one .md or .mdx file', () => {
    const files = getAllFiles(docsDir);
    const docFiles = files.filter(
      (f) => f.endsWith('.md') || f.endsWith('.mdx')
    );
    expect(docFiles.length).toBeGreaterThan(0);
  });

  test('docs/index.mdx exists (landing page)', () => {
    const indexPath = path.join(docsDir, 'index.mdx');
    expect(fs.existsSync(indexPath)).toBe(true);
  });

  test('all .md/.mdx files are non-empty', () => {
    const files = getAllFiles(docsDir);
    const docFiles = files.filter(
      (f) => f.endsWith('.md') || f.endsWith('.mdx')
    );
    const emptyFiles: string[] = [];
    for (const file of docFiles) {
      const content = fs.readFileSync(file, 'utf-8').trim();
      if (content.length === 0) {
        emptyFiles.push(path.relative(ROOT, file));
      }
    }
    expect(emptyFiles).toEqual([]);
  });
});

describe('Required directories', () => {
  test.each(['src', 'static', 'docs'])('%s/ directory exists', (dir) => {
    const dirPath = path.join(ROOT, dir);
    expect(fs.existsSync(dirPath)).toBe(true);
  });
});

describe('Package configuration', () => {
  test('package.json exists and has build script', () => {
    const pkgPath = path.join(ROOT, 'package.json');
    expect(fs.existsSync(pkgPath)).toBe(true);
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    expect(pkg.scripts).toBeDefined();
    expect(pkg.scripts.build).toBeDefined();
  });

  test('package.json has docusaurus dependencies', () => {
    const pkg = JSON.parse(
      fs.readFileSync(path.join(ROOT, 'package.json'), 'utf-8')
    );
    expect(pkg.dependencies['@docusaurus/core']).toBeDefined();
    expect(pkg.dependencies['@docusaurus/preset-classic']).toBeDefined();
  });

  test('tsconfig.json exists', () => {
    expect(fs.existsSync(path.join(ROOT, 'tsconfig.json'))).toBe(true);
  });
});

describe('Custom CSS', () => {
  test('custom.css exists', () => {
    const cssPath = path.join(ROOT, 'src', 'css', 'custom.css');
    expect(fs.existsSync(cssPath)).toBe(true);
  });
});

// ── Helpers ──────────────────────────────────────────────────────────────────

function getAllFiles(dir: string): string[] {
  const results: string[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...getAllFiles(fullPath));
    } else {
      results.push(fullPath);
    }
  }
  return results;
}
